---
- hosts: all
  become: yes
  tasks:

    - name: add fail2ban group
      group:
        name: fail2ban
        state: present

    - name: add zabbix user to fail2ban group
      user:
        name: zabbix
        groups: fail2ban
        append: yes

    - name: add zabbix userparameter for fail2ban
      tags:
         - userparameter   
      copy:
        src: fail2ban.conf
        dest: /etc/zabbix/zabbix_agentd.d/fail2ban.conf

    - name: restart zabbix-agent
      tags:
         - userparameter   
      service:
        name: zabbix-agent
        state: restarted

    - name: create directory for scripts
      file:
        path: /root/scripts
        state: directory

    - name: create script to make the group ownership and permissions of fail2ban socket
      template:
        src: script/fail2ban-socket-perms.sh
        dest: /root/scripts/fail2ban-socket-perms.sh
        mode: a+x

    - name: permissions over fail2ban socket cronjob
      cron: 
        name: set permissions for fail2ban socket
        minute: 0
        hour: '*'
        job: /root/scripts/fail2ban-socket-perms.sh
